# Rose Pine
# Theme create by: https://github.com/pearcidar
# Update by(sort by time):
# 
# Thanks for all contributor!!

# If you want to make border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = 

# ========= Border =========
file_panel_border = #9d0006
sidebar_border = #9d0006
footer_border = #9d0006

# ========= Border Active =========
file_panel_border_active = #9d0006
sidebar_border_active = #9d0006
footer_border_active = #9d0006
modal_border_active = #9d0006

# ========= Background (bg) =========
full_screen_bg = #9d0006
file_panel_bg = #9d0006
sidebar_bg = #9d0006
footer_bg = #9d0006
modal_bg = #9d0006

# ========= Foreground (fg) =========
full_screen_fg = #9d0006
file_panel_fg = #9d0006
sidebar_fg = #9d0006
footer_fg = #9d0006
modal_fg = #9d0006

# ========= Special Color =========
cursor = #9ccfd8
correct = #9d0006
error = #ff6969
hint = #31784f
cancel = #9d0006
# Gradient color can only have two color!
gradient_color = [ #31784f, #eb6f92]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = #9ccfd8
file_panel_top_path = #ebbcba
file_panel_item_selected_fg = #c4a7e7
file_panel_item_selected_bg = #689d6a

# ========= Sidebar Special Items =========
sidebar_title = #6e6e86
sidebar_item_selected_fg = #f6c177
sidebar_item_selected_bg = #689d6a
sidebar_divider = #868686

# ========= Modal Special Items =========
modal_cancel_fg = #689d6a
modal_cancel_bg = #524f67

modal_confirm_fg = #689d6a
modal_confirm_bg = #eb6f92

# ========= Help Menu =========
help_menu_hotkey = #f6c177
help_menu_title = #9ccfd8
