# Tokyonight
# Theme create by: https://github.com/pearcidar
# Update by(sort by time):
# 
# Thanks for all contributor!!

# If you want to make border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "catppuccin-macchiato"

# ========= Border =========
file_panel_border = "#7aa2f7"
sidebar_border = "#7aa2f7"
footer_border = "#7aa2f7"

# ========= Border Active =========
file_panel_border_active = "#0abdc6"
sidebar_border_active = "#0abdc6"
footer_border_active = "#0abdc6"
modal_border_active = "#0abdc6"

# ========= Background (bg) =========
full_screen_bg = "#000b1e"
file_panel_bg = "#000b1e"
sidebar_bg = "#000b1e"
footer_bg = "#000b1e"
modal_bg = "#000b1e"

# ========= Foreground (fg) =========
full_screen_fg = "#a9b1d6"
file_panel_fg = "#a9b1d6"
sidebar_fg = "#a9b1d6"
footer_fg = "#a9b1d6"
modal_fg = "#a9b1d6"

# ========= Special Color =========
cursor = "#00a138"
correct = "#9ece6a"
error = "#f7768e"
hint = "#a9b1d6"
cancel = "#00a138"
# Gradient color can only have two color!
gradient_color = ["#7aa2f7", "#bb9af7"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#0abdc6"
file_panel_top_path = "#7aa2f7"
file_panel_item_selected_fg = "#2ac3de"
file_panel_item_selected_bg = "#000b1e"

# ========= Sidebar Special Items =========
sidebar_title = "#0abdc6"
sidebar_item_selected_fg = "#a9b1d6"
sidebar_item_selected_bg = "#000b1e"
sidebar_divider = "#565f89"

# ========= Modal Special Items =========
modal_cancel_fg = "#24383b"
modal_cancel_bg = "#e0af68"

modal_confirm_fg = "#414868"
modal_confirm_bg = "#9ece6a"

# ========= Help Menu =========
help_menu_hotkey = "#a9b1d6"
help_menu_title = "#0abdc6"
